destination: ./_site
auto:        false
lsi:         false
markdown:    maruku
permalink:   date
maruku:
  use_tex:    true
  use_divs:   false
  png_dir:    images/latex/
  png_url:    /images/latex/