auto:        true
lsi:         false
pygments:    true
markdown:    maruku
permalink:   date
maruku:
  use_tex:    true
  use_divs:   false
  png_dir:    site/images/latex/
  png_url:    /images/latex/